/*
 * This file is generated by jOOQ.
 */
package com.zxc.cxc.web.jooq;


import com.zxc.cxc.web.jooq.tables.HomePageInfo;
import com.zxc.cxc.web.jooq.tables.records.HomePageInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * zixiDatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HomePageInfoRecord> KEY_HOME_PAGE_INFO_PRIMARY = Internal.createUniqueKey(HomePageInfo.HOME_PAGE_INFO, DSL.name("KEY_home_page_info_PRIMARY"), new TableField[] { HomePageInfo.HOME_PAGE_INFO.ID }, true);
}
