/*
 * This file is generated by jOOQ.
 */
package com.zxc.cxc.web.jooq;


import com.zxc.cxc.web.jooq.tables.HomePageInfo;


/**
 * Convenience access to all tables in zixiDatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>zixiDatabase.home_page_info</code>.
     */
    public static final HomePageInfo HOME_PAGE_INFO = HomePageInfo.HOME_PAGE_INFO;
}
