/*
 * This file is generated by jOOQ.
 */
package com.zxc.cxc.web.jooq;


import com.zxc.cxc.web.jooq.tables.HomePageInfo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Zixidatabase extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>zixiDatabase</code>
     */
    public static final Zixidatabase ZIXIDATABASE = new Zixidatabase();

    /**
     * The table <code>zixiDatabase.home_page_info</code>.
     */
    public final HomePageInfo HOME_PAGE_INFO = HomePageInfo.HOME_PAGE_INFO;

    /**
     * No further instances allowed
     */
    private Zixidatabase() {
        super("zixiDatabase", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            HomePageInfo.HOME_PAGE_INFO
        );
    }
}
