/*
 * This file is generated by jOOQ.
 */
package com.zxc.cxc.web.jooq.tables.records;


import com.zxc.cxc.web.jooq.tables.HomePageInfo;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HomePageInfoRecord extends UpdatableRecordImpl<HomePageInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>zixiDatabase.home_page_info.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.intro</code>. Intro
     */
    public void setIntro(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.intro</code>. Intro
     */
    public String getIntro() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.sub_intro</code>. Sub Intro
     */
    public void setSubIntro(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.sub_intro</code>. Sub Intro
     */
    public String getSubIntro() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.avatar</code>. Avatar
     */
    public void setAvatar(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.avatar</code>. Avatar
     */
    public String getAvatar() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.create_time</code>. Creation
     * Time
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.create_time</code>. Creation
     * Time
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.update_time</code>. Update
     * Time
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.update_time</code>. Update
     * Time
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>zixiDatabase.home_page_info.deleted</code>. Logical
     * Deletion
     */
    public void setDeleted(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>zixiDatabase.home_page_info.deleted</code>. Logical
     * Deletion
     */
    public Byte getDeleted() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HomePageInfoRecord
     */
    public HomePageInfoRecord() {
        super(HomePageInfo.HOME_PAGE_INFO);
    }

    /**
     * Create a detached, initialised HomePageInfoRecord
     */
    public HomePageInfoRecord(Long id, String intro, String subIntro, String avatar, LocalDateTime createTime, LocalDateTime updateTime, Byte deleted) {
        super(HomePageInfo.HOME_PAGE_INFO);

        setId(id);
        setIntro(intro);
        setSubIntro(subIntro);
        setAvatar(avatar);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setDeleted(deleted);
        resetChangedOnNotNull();
    }
}
