openapi: 3.0.3
info:
  version: 1.0.0
  title: ZXC CXC Web
  description: The response type of APIs are wrapped by "BaseResponse" type
servers:
  - url: http://127.0.0.1:9010/
tags:
  - name: homepage
paths:
  /homepage/info:
    $ref: ./paths/homepage/info.yml
components:
  schemas:
    $ref: ./schemas/_index.yaml
  responses:
    $ref: ./responses/_index.yaml
